changelog:
  categories:
    - title: ⚠️ Breaking Changes ⚠️
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
    - title: Dependencies
      labels:
        - dependencies
