---
kind: pipeline
type: docker
name: build_go

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: gcp-vault

steps:
  - name: test
    image: golang:1.19
    commands:
      - go test -v ./... -covermode=count .
    when:
      event:
        - push
